# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: actuator.proto for package ''

require 'grpc'
require 'actuator_pb'

module Actuator
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Actuator'

    rpc :setRemote, ::State, ::State
  end

  Stub = Service.rpc_stub_class
end
