# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actuator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("actuator.proto", :syntax => :proto3) do
    add_message "State" do
      optional :flag, :bool, 1
      optional :level, :int32, 2
    end
  end
end

State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("State").msgclass
